%YAML:1.0
cameraMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [240.225, 0, 323.687,
        0, 241.104, 217.629,
        0, 0, 1]

distCoeffs: !!opencv-matrix
   rows: 1
   cols: 4
   dt: d
   data: [0, 0, 0, 0]
